## Chapter 4: Linear algebra

In [18]:
import numpy as np

**Vector $\vec{v}$ has a value of [1, 2] but then a transformation happens. $\hat{j}$ lands at [2, 0] and $\hat{i}$ lands at [0, 1.5]. Where does $\vec{v}$ land?**

In [19]:
v = np.array([1,2])
i_hat = np.array([2, 0])
j_hat = np.array([0, 1.5])

combined = np.array([i_hat, j_hat])

w = combined.dot(v)

w

array([2., 3.])

**Vector $\vec{v}$ has a value of [1, 2] but then a transformation happens. $\hat{i}$ lands at [2, 1] and $\hat{j}$ lands at [1, -2]. Where does $\vec{v}$ land?**

In [20]:
v = np.array([1,2])
i_hat = np.array([-2, 1])
j_hat = np.array([1, -2])

combined = np.array([i_hat, j_hat])

w = combined.dot(v)

w

array([ 0, -3])

**A transformation $\hat{i}$ lands at [1,0] and $\hat{j}$ lands at [2,2]. What is the determinant of this transformation?**

In [21]:
i_hat = np.array([1, 0])
j_hat = np.array([2, 2])

combined = np.array([i_hat, j_hat])

det = np.linalg.det(combined)
det

np.float64(2.0)

**Can two or more linear transformations be done in single linear transformation? Why or why not?**

Yes, cause with lineair algebra you can combine matrices and then transform so you transform multiple matrices cause they are combined.

**Solve the system of equations for x, y, and z:**  
**3x + 1y + 0z = 54**  
**2x + 4y + 1z = 12**  
**3x + 1y + 8z = 6**

In [ ]:
A = np.array([[3,1,0],[2,4,1],[3,1,8]])
B = np.array([54,12,6])
X = np.linalg.inv(A).dot(B)

X

array([19.8, -5.4, -6. ])

**Is the following matrix linearly dependent? Why or why not?**  
**[2 1]**  
**[6 3]**

In [23]:
#The following matrix is linearly dependent when the det is 0
i_hat = np.array([2, 1])
j_hat = np.array([6, 3])

combined = np.array([i_hat, j_hat])

det = np.linalg.det(combined)
det
# Conclusion: The determinant is 0 so the matrix is linearly dependent.

np.float64(0.0)